version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: ..
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    driver: local
